### ISSUE TITLE
Alphabetical Sorting

### ISSUE THREAD

**Issue by ruppysuppy** [okulbilisim/awesome-datascience#190]
The contents would seem more organized if it was sorted alphabetically (the links in the section like MOOCs, Data Sets, etc.)

**Comment by SourangshuGhosh** [comment]
I can work out on this if the administrator of this repository give me permission to submit PR on this issue.

**Comment by hmert** [comment]
@SourangshuGhosh you don't need an permission to submit PR.

**Comment by SourangshuGhosh** [comment]
Okay sir I will submit a PR on this after you will review my earlier Draft PR

**Comment by hmert** [comment]
Sure.

**Comment by SourangshuGhosh** [comment]
Respected Sir,
Shall I rearrange the contents categorically under each section or the whole read me file.  I think rearranging it categorically will be better.

**Comment by hmert** [comment]
Hello, feel free to contribute #209
