### ISSUE TITLE
Check the Repo of Data Science

### ISSUE THREAD

**Issue by BIGG000** [okulbilisim/awesome-datascience#207]
Hey Guys
 I just made a great repo about Data Science and its tool, so that repo need some alternation it would be great if you guys check that out and drop your suggestion so I'll add your point on it.
Thanks ❤️ 

**https://github.com/BIGG000/Data-Science-Learning-Track**

**Comment by hmert** [comment]
@BIGG000 in your repo there are Codecademy's materials. Are you sure those are copyrighted?

**Comment by BIGG000** [comment]
Thanks for checking, ya codeacademy material and Google stuff as well... I didn't share full material of codeacademy.

**Comment by hmert** [comment]
But you shouldn't share any of their material.
