### ISSUE TITLE
Data Science vs. Machine Learning

### ISSUE THREAD

**Issue by 0asa** [okulbilisim/awesome-datascience#23]
Both are awesome but there is a large overlap between these two: 

- https://github.com/okulbilisim/awesome-datascience
- https://github.com/josephmisiti/awesome-machine-learning

What would be the key differentiators?
Any plan to merge the two awesome repos?

**Comment by erolrecep** [comment]
Awesome-datascience repo is designed for data science application guide and structured for a data science project creation process. There are 6 different sections to build a data science project. Additionally, Data science life cycle is prepared for whole data science application process according to step by step challenges. If you look at "Apply algorithm to fix problem" part is just for Data mining and machine learning process. All in all, if you want to merge awesome-machine-learning repo with https://github.com/okulbilisim/awesome-datascience/blob/master/DataScience-Life-Cycle.md#apply-algorithm-to-fix-problem section we are open.

**Comment by hmert** [comment]
BTW, awesome-datascience not only a list but also a guide for whom try to learn this topic. We will set webinars and courses soon :)
