### ISSUE TITLE
website

### ISSUE THREAD

**Issue by necatikartal** [okulbilisim/awesome-datascience#29]
i would like to do that :+1:

**Comment by hmert** [comment]
do it

**Comment by hmert** [comment]
@necatikartal I've created website gh-page branch http://okulbilisim.github.io/awesome-datascience/

Düde, it's your turn!

**Comment by necatikartal** [comment]
Ok, I'll do it as soon as I can! :+1:

**Comment by hmert** [comment]
you have only 7 days to do it :) my little intern :clock1: :bomb:

**Comment by necatikartal** [comment]
it's on the way :+1:

**Comment by hmert** [comment]
bump

**Comment by necatikartal** [comment]
working on it; layout is ready but content and some fixes are still missing.

**Comment by hmert** [comment]
:bomb:
