### ISSUE TITLE
New book: Julia for data Science

### ISSUE THREAD

**Issue by ilkerarslan** [okulbilisim/awesome-datascience#397]
Hi, 

My book Julia for Data Science is published by Manning this week.
The link for the book is: [http://mng.bz/x4vd](https://shortener.manning.com/x4vd)
I would be very happy if you kindly consider adding my book to the list of resources.

In addition I also have a Programming with Julia course on Udemy if you kindly want to consider for adding to the resource list: https://www.udemy.com/course/programming-with-julia/

Many thanks.

**Comment by fakturk** [comment]
Hi @ilkerarslan ,
Julia for Datascience book already added in this PR https://github.com/academic/awesome-datascience/pull/396/commits/4480b3b5af57ae6d011ff3ecc49539c8dd21961e

However you can create a new PR and add Udemy Course :)
Best,
Fatih

**Comment by ilkerarslan** [comment]
Thank you very much.

**Comment by cesschneider** [comment]
@ilkerarslan I'm very interested to learn more about Data Science tools and Julia.
Just bought your course on Udemy. =)

**Comment by ilkerarslan** [comment]
I hope you liked it. Please kindly share your feedback with me so that I can improve it :)
