### ISSUE TITLE
Add jax

### ISSUE THREAD

**Issue by kevin1kevin1k** [okulbilisim/awesome-datascience#447]
Jax has been gaining popularity these days, and I think it's good to also introduce it here.
Not quite sure if it should be added under the section `The Data Science Toolbox / General Machine Learning Packages` or `The Data Science Toolbox / Deep Learning Packages` though.

**Comment by hmert** [comment]
@kevin1kevin1k could you make a PR for this?

**Comment by kevin1kevin1k** [comment]
Sure! And by the way I decided to add more stuff than just jax.
